import process from 'process';

import builtins from 'builtin-modules';
import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source available at the plugin repo.
*/`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', 'child_process', 'util', 'fs', 'os', 'path', ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  loader: { '.js': 'text' }
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
